### ISSUE TITLE
Seems to be 500ing pretty much ALL THE TIME

### ISSUE THREAD

**Issue by anjackson** [ukwa/webrender-puppeteer#22]
```
root@npld-heritrix3-worker-1:/home/heritrix# curl "http://webrender:8010/render?url=https://fullfact.org/health/&warc_prefix=TEST-TMP"
Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
```

From the logs...

```
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"BL-NPLD-WEBRENDER-frequent-npld-20220606093552\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ cluster.task running render with warcPrefix=TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | render_page got warcPrefix: TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Sent Fetch.enable, extraHeaders = {"Warcprox-Meta":"{\"warc-prefix\":\"TEST-TMP\"}"}
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Set up interception for https://fullfact.org/health/ and extraHeaders {"Warcprox-Meta":"{\"warc-prefix\":\"TEST-TMP\"}"}.
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | switchDevices = false
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | runBehaviours = true
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Default User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.
36
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Setting User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.
36 bl.uk_ldfc_renderbot/2.1.0 (+https://www.bl.uk/legal-deposit/web-archiving)
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Navigating to https://fullfact.org/health/...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Waiting for delayed popups...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Looking for any modal buttons...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Waiting for any activity to die down...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Scrolling down...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Scrolling back to the top...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Setting viewport: 1366x6314
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Waiting for any activity to die down...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Rendering web page as PNG...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Rendering screenshot as JPEG...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | https://fullfact.org/health/ - Rendering PDF...
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Attempting to POST data for har:https://fullfact.org/health/ with warcPrefix TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Attempting to POST data for onreadydom:https://fullfact.org/health/ with warcPrefix TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Attempting to POST data for screenshot:https://fullfact.org/health/ with warcPrefix TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | GOT temp path: /tmp/s-2022621-1-1sb3uww.fpa5i
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | PIPED to temp path: /tmp/s-2022621-1-1sb3uww.fpa5i
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Opening Readable Stream /tmp/s-2022621-1-1sb3uww.fpa5i
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Attempting to POST data for pdf:https://fullfact.org/health/ with warcPrefix TEST-TMP
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | Deleting temp file: /tmp/s-2022621-1-1sb3uww.fpa5i
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    | ReferenceError: imageJpeg is not defined
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    |     at render_page (/app/renderer.js:360:52)
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    |     at runMicrotasks (<anonymous>)
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
fc_crawl_webrender.1.yzyg2u2v5z9t@crawler06    |     at async /app/server.js:90:15
```

**Comment by anjackson** [comment]
Secondary issue:

```
Caught unhandledRejection:  Protocol error (Target.attachToTarget): Target closed. Promise {
  <rejected> ProtocolError: Protocol error (Target.attachToTarget): Target closed.
      at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:97:24
      at new Promise (<anonymous>)
      at Connection.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:93:16)
      at Connection.createSession (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:122:42)
      at Target.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:425:71)
      at Target.createCDPSession (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:89:74)
      at interceptAllTrafficForPageUsingFetch (/app/renderer.js:54:33)
      at interceptor (/app/renderer.js:101:11)
      at /app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:68
      at Array.map (<anonymous>) {
    originalMessage: ''
  }
}
```

**Comment by anjackson** [comment]
Main issue seems to be that `imageJpeg` has become locally scoped to the new `if` construct:

https://github.com/ukwa/webrender-puppeteer/blob/ee6fa8ea7ff1462ebba5cfc829290e667a48d6d4/renderer.js#L265

So can't be used later.  Needs to be a `var` in the outer scope.

**Comment by anjackson** [comment]
Hah, note that this one works:

https://github.com/ukwa/webrender-puppeteer/blob/ee6fa8ea7ff1462ebba5cfc829290e667a48d6d4/renderer.js#L271

Because `var` is scoped to the surrounding function, and is not block scoped, but `const` and `let` are block scoped. Well.
